# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.4.3

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
RUN kibana-plugin install https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/artifacts/kibana5/raw/artifact/elastalert-5.4.3-latest.zip?job=build
